# Generated by Django 3.0.8 on 2020-07-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200730_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mar_returned', 'Set book as returned'),)},
        ),
    ]
